"""
TPT Categories — structure officielle avec niveau de popularité.
pages=3 → populaire, pages=2 → moyen, pages=1 → niche
Total estimé : ~930 requêtes ScrapingBee (3 tris × pages × catégories)
"""

TPT_LEAF_CATEGORIES = [

    # ─── GRADE ────────────────────────────────────────────────────────────────
    {"id": "preschool",     "name": "Preschool",     "url": "/browse/elementary/preschool",    "parent": "Grade", "pages": 2},
    {"id": "kindergarten",  "name": "Kindergarten",  "url": "/browse/elementary/kindergarten", "parent": "Grade", "pages": 3},
    {"id": "1st-grade",     "name": "1st Grade",     "url": "/browse/elementary/1st-grade",    "parent": "Grade", "pages": 3},
    {"id": "2nd-grade",     "name": "2nd Grade",     "url": "/browse/elementary/2nd-grade",    "parent": "Grade", "pages": 3},
    {"id": "3rd-grade",     "name": "3rd Grade",     "url": "/browse/elementary/3rd-grade",    "parent": "Grade", "pages": 3},
    {"id": "4th-grade",     "name": "4th Grade",     "url": "/browse/elementary/4th-grade",    "parent": "Grade", "pages": 3},
    {"id": "5th-grade",     "name": "5th Grade",     "url": "/browse/elementary/5th-grade",    "parent": "Grade", "pages": 3},
    {"id": "6th-grade",     "name": "6th Grade",     "url": "/browse/middle-school/6th-grade", "parent": "Grade", "pages": 2},
    {"id": "7th-grade",     "name": "7th Grade",     "url": "/browse/middle-school/7th-grade", "parent": "Grade", "pages": 2},
    {"id": "8th-grade",     "name": "8th Grade",     "url": "/browse/middle-school/8th-grade", "parent": "Grade", "pages": 2},
    {"id": "9th-grade",     "name": "9th Grade",     "url": "/browse/high-school/9th-grade",   "parent": "Grade", "pages": 1},
    {"id": "10th-grade",    "name": "10th Grade",    "url": "/browse/high-school/10th-grade",  "parent": "Grade", "pages": 1},
    {"id": "11th-grade",    "name": "11th Grade",    "url": "/browse/high-school/11th-grade",  "parent": "Grade", "pages": 1},
    {"id": "12th-grade",    "name": "12th Grade",    "url": "/browse/high-school/12th-grade",  "parent": "Grade", "pages": 1},
    {"id": "adult-education","name": "Adult Education","url": "/browse/adult-education",        "parent": "Grade", "pages": 1},

    # ─── RESOURCE TYPE ────────────────────────────────────────────────────────
    {"id": "worksheets",            "name": "Worksheets",             "url": "/browse/student-practice/worksheets",              "parent": "Resource Type", "pages": 3},
    {"id": "task-cards",            "name": "Task Cards",             "url": "/browse/student-practice/task-cards",              "parent": "Resource Type", "pages": 3},
    {"id": "assessment",            "name": "Assessment",             "url": "/browse/student-assessment/assessment",            "parent": "Resource Type", "pages": 3},
    {"id": "graphic-organizers",    "name": "Graphic Organizers",     "url": "/browse/student-practice/graphic-organizers",      "parent": "Resource Type", "pages": 2},
    {"id": "independent-work",      "name": "Independent Work Packet","url": "/browse/student-practice/independent-work-packet", "parent": "Resource Type", "pages": 2},
    {"id": "flash-cards",           "name": "Flash Cards",            "url": "/browse/student-practice/flash-cards",             "parent": "Resource Type", "pages": 2},
    {"id": "games",                 "name": "Games",                  "url": "/browse/hands-on-activities/games",                "parent": "Resource Type", "pages": 3},
    {"id": "centers",               "name": "Centers",                "url": "/browse/hands-on-activities/centers",              "parent": "Resource Type", "pages": 3},
    {"id": "projects",              "name": "Projects",               "url": "/browse/hands-on-activities/projects",             "parent": "Resource Type", "pages": 2},
    {"id": "laboratory",            "name": "Laboratory",             "url": "/browse/hands-on-activities/laboratory",           "parent": "Resource Type", "pages": 1},
    {"id": "songs",                 "name": "Songs",                  "url": "/browse/hands-on-activities/songs",                "parent": "Resource Type", "pages": 1},
    {"id": "classroom-management",  "name": "Classroom Management",   "url": "/browse/teacher-tools/classroom-management",       "parent": "Resource Type", "pages": 3},
    {"id": "lessons",               "name": "Lessons",                "url": "/browse/teacher-tools/lessons",                    "parent": "Resource Type", "pages": 2},
    {"id": "unit-plans",            "name": "Unit Plans",             "url": "/browse/teacher-tools/unit-plans",                 "parent": "Resource Type", "pages": 2},
    {"id": "rubrics",               "name": "Rubrics",                "url": "/browse/teacher-tools/rubrics",                    "parent": "Resource Type", "pages": 1},
    {"id": "outlines",              "name": "Outlines",               "url": "/browse/teacher-tools/outlines",                   "parent": "Resource Type", "pages": 1},
    {"id": "syllabi",               "name": "Syllabi",                "url": "/browse/teacher-tools/syllabi",                    "parent": "Resource Type", "pages": 1},
    {"id": "teacher-manuals",       "name": "Teacher Manuals",        "url": "/browse/teacher-tools/teacher-manuals",            "parent": "Resource Type", "pages": 1},
    {"id": "clip-art",              "name": "Clip Art",               "url": "/browse/clip-art",                                 "parent": "Resource Type", "pages": 2},
    {"id": "bulletin-board-ideas",  "name": "Bulletin Board Ideas",   "url": "/browse/classroom-decor/bulletin-board-ideas",     "parent": "Resource Type", "pages": 2},
    {"id": "posters",               "name": "Posters",                "url": "/browse/classroom-decor/posters",                  "parent": "Resource Type", "pages": 2},
    {"id": "word-walls",            "name": "Word Walls",             "url": "/browse/classroom-decor/word-walls",               "parent": "Resource Type", "pages": 1},
    {"id": "printables",            "name": "Printables",             "url": "/browse/printables",                               "parent": "Resource Type", "pages": 3},

    # ─── SEASONAL ─────────────────────────────────────────────────────────────
    {"id": "back-to-school",            "name": "Back to School",           "url": "/browse/seasonal/back-to-school",                    "parent": "Seasonal", "pages": 3},
    {"id": "halloween",                 "name": "Halloween",                "url": "/browse/holiday/halloween",                          "parent": "Seasonal", "pages": 3},
    {"id": "christmas-chanukah-kwanzaa","name": "Christmas / Chanukah",     "url": "/browse/holiday/christmas-chanukah-kwanzaa",          "parent": "Seasonal", "pages": 3},
    {"id": "thanksgiving",              "name": "Thanksgiving",             "url": "/browse/holiday/thanksgiving",                       "parent": "Seasonal", "pages": 3},
    {"id": "valentines-day",            "name": "Valentine's Day",          "url": "/browse/holiday/valentines-day",                     "parent": "Seasonal", "pages": 3},
    {"id": "end-of-year",               "name": "End of Year",              "url": "/browse/seasonal/end-of-year",                       "parent": "Seasonal", "pages": 2},
    {"id": "earth-day",                 "name": "Earth Day",                "url": "/browse/holiday/earth-day",                          "parent": "Seasonal", "pages": 2},
    {"id": "st-patricks-day",           "name": "St. Patrick's Day",        "url": "/browse/holiday/st-patricks-day",                    "parent": "Seasonal", "pages": 2},
    {"id": "easter",                    "name": "Easter",                   "url": "/browse/holiday/easter",                             "parent": "Seasonal", "pages": 2},
    {"id": "black-history-month",       "name": "Black History Month",      "url": "/browse/holiday/black-history-month",                "parent": "Seasonal", "pages": 2},
    {"id": "martin-luther-king-day",    "name": "Martin Luther King Day",   "url": "/browse/holiday/martin-luther-king-day",             "parent": "Seasonal", "pages": 1},
    {"id": "presidents-day",            "name": "Presidents' Day",          "url": "/browse/holiday/presidents-day",                     "parent": "Seasonal", "pages": 1},
    {"id": "hispanic-heritage-month",   "name": "Hispanic Heritage Month",  "url": "/browse/holiday/hispanic-heritage-month",            "parent": "Seasonal", "pages": 1},
    {"id": "womens-history-month",      "name": "Women's History Month",    "url": "/browse/holiday/womens-history-month",               "parent": "Seasonal", "pages": 1},
    {"id": "new-year",                  "name": "New Year",                 "url": "/browse/holiday/new-year",                           "parent": "Seasonal", "pages": 1},
    {"id": "autumn",                    "name": "Autumn",                   "url": "/browse/seasonal/autumn",                            "parent": "Seasonal", "pages": 2},
    {"id": "winter",                    "name": "Winter",                   "url": "/browse/seasonal/winter",                            "parent": "Seasonal", "pages": 2},
    {"id": "spring",                    "name": "Spring",                   "url": "/browse/seasonal/spring",                            "parent": "Seasonal", "pages": 2},
    {"id": "summer",                    "name": "Summer",                   "url": "/browse/seasonal/summer",                            "parent": "Seasonal", "pages": 2},

    # ─── ELA ──────────────────────────────────────────────────────────────────
    {"id": "kindergarten-ela",  "name": "Kindergarten ELA",  "url": "/browse/elementary/kindergarten/english-language-arts", "parent": "ELA", "pages": 3},
    {"id": "1st-grade-ela",     "name": "1st Grade ELA",     "url": "/browse/elementary/1st-grade/english-language-arts",    "parent": "ELA", "pages": 3},
    {"id": "2nd-grade-ela",     "name": "2nd Grade ELA",     "url": "/browse/elementary/2nd-grade/english-language-arts",    "parent": "ELA", "pages": 3},
    {"id": "3rd-grade-ela",     "name": "3rd Grade ELA",     "url": "/browse/elementary/3rd-grade/english-language-arts",    "parent": "ELA", "pages": 3},
    {"id": "4th-grade-ela",     "name": "4th Grade ELA",     "url": "/browse/elementary/4th-grade/english-language-arts",    "parent": "ELA", "pages": 3},
    {"id": "5th-grade-ela",     "name": "5th Grade ELA",     "url": "/browse/elementary/5th-grade/english-language-arts",    "parent": "ELA", "pages": 2},
    {"id": "6th-grade-ela",     "name": "6th Grade ELA",     "url": "/browse/middle-school/6th-grade/english-language-arts", "parent": "ELA", "pages": 2},
    {"id": "7th-grade-ela",     "name": "7th Grade ELA",     "url": "/browse/middle-school/7th-grade/english-language-arts", "parent": "ELA", "pages": 2},
    {"id": "8th-grade-ela",     "name": "8th Grade ELA",     "url": "/browse/middle-school/8th-grade/english-language-arts", "parent": "ELA", "pages": 2},
    {"id": "high-school-ela",   "name": "High School ELA",   "url": "/browse/high-school/english-language-arts",             "parent": "ELA", "pages": 2},
    {"id": "preschool-ela",     "name": "Preschool ELA",     "url": "/browse/elementary/preschool/english-language-arts",    "parent": "ELA", "pages": 1},
    {"id": "ela-reading",       "name": "Reading",           "url": "/browse/elementary/english-language-arts/reading",      "parent": "ELA", "pages": 3},
    {"id": "ela-writing",       "name": "Writing (Elem)",    "url": "/browse/elementary/english-language-arts/writing",      "parent": "ELA", "pages": 3},
    {"id": "phonics",           "name": "Phonics",           "url": "/browse/elementary/english-language-arts/phonics-and-phonological-awareness", "parent": "ELA", "pages": 3},
    {"id": "grammar",           "name": "Grammar",           "url": "/browse/elementary/english-language-arts/grammar",      "parent": "ELA", "pages": 3},
    {"id": "ela-vocabulary",    "name": "Vocabulary",        "url": "/browse/elementary/english-language-arts/vocabulary",   "parent": "ELA", "pages": 2},
    {"id": "spelling",          "name": "Spelling",          "url": "/browse/elementary/english-language-arts/spelling",     "parent": "ELA", "pages": 2},
    {"id": "poetry",            "name": "Poetry",            "url": "/browse/elementary/english-language-arts/poetry",       "parent": "ELA", "pages": 1},
    {"id": "ela-test-prep",     "name": "ELA Test Prep",     "url": "/browse/elementary/english-language-arts/ela-test-prep","parent": "ELA", "pages": 2},
    {"id": "ms-ela-literature", "name": "MS Literature",     "url": "/browse/middle-school/english-language-arts/literature","parent": "ELA", "pages": 2},
    {"id": "ms-ela-writing",    "name": "MS Writing",        "url": "/browse/middle-school/english-language-arts/writing",   "parent": "ELA", "pages": 2},
    {"id": "ms-ela-essays",     "name": "MS Essays",         "url": "/browse/middle-school/english-language-arts/writing-essays", "parent": "ELA", "pages": 1},
    {"id": "hs-ela-literature", "name": "HS Literature",     "url": "/browse/high-school/english-language-arts/literature",  "parent": "ELA", "pages": 2},
    {"id": "hs-ela-writing",    "name": "HS Writing",        "url": "/browse/high-school/english-language-arts/writing",     "parent": "ELA", "pages": 1},

    # ─── MATH ─────────────────────────────────────────────────────────────────
    {"id": "kindergarten-math", "name": "Kindergarten Math", "url": "/browse/elementary/kindergarten/math", "parent": "Math", "pages": 3},
    {"id": "1st-grade-math",    "name": "1st Grade Math",    "url": "/browse/elementary/1st-grade/math",    "parent": "Math", "pages": 3},
    {"id": "2nd-grade-math",    "name": "2nd Grade Math",    "url": "/browse/elementary/2nd-grade/math",    "parent": "Math", "pages": 3},
    {"id": "3rd-grade-math",    "name": "3rd Grade Math",    "url": "/browse/elementary/3rd-grade/math",    "parent": "Math", "pages": 3},
    {"id": "4th-grade-math",    "name": "4th Grade Math",    "url": "/browse/elementary/4th-grade/math",    "parent": "Math", "pages": 3},
    {"id": "5th-grade-math",    "name": "5th Grade Math",    "url": "/browse/elementary/5th-grade/math",    "parent": "Math", "pages": 3},
    {"id": "6th-grade-math",    "name": "6th Grade Math",    "url": "/browse/middle-school/6th-grade/math", "parent": "Math", "pages": 3},
    {"id": "7th-grade-math",    "name": "7th Grade Math",    "url": "/browse/middle-school/7th-grade/math", "parent": "Math", "pages": 2},
    {"id": "8th-grade-math",    "name": "8th Grade Math",    "url": "/browse/middle-school/8th-grade/math", "parent": "Math", "pages": 2},
    {"id": "high-school-math",  "name": "High School Math",  "url": "/browse/high-school/math",             "parent": "Math", "pages": 2},
    {"id": "preschool-math",    "name": "Preschool Math",    "url": "/browse/elementary/preschool/math",    "parent": "Math", "pages": 1},
    {"id": "basic-operations",  "name": "Basic Operations",  "url": "/browse/elementary/math/basic-operations", "parent": "Math", "pages": 3},
    {"id": "fractions",         "name": "Fractions",         "url": "/browse/elementary/math/fractions",        "parent": "Math", "pages": 3},
    {"id": "place-value",       "name": "Place Value",       "url": "/browse/elementary/math/place-value",      "parent": "Math", "pages": 3},
    {"id": "measurement",       "name": "Measurement",       "url": "/browse/elementary/math/measurement",      "parent": "Math", "pages": 2},
    {"id": "geometry-elem",     "name": "Geometry (Elem)",   "url": "/browse/elementary/math/geometry",         "parent": "Math", "pages": 2},
    {"id": "numbers",           "name": "Numbers",           "url": "/browse/elementary/math/numbers",           "parent": "Math", "pages": 2},
    {"id": "decimals",          "name": "Decimals",          "url": "/browse/elementary/math/decimals",          "parent": "Math", "pages": 2},
    {"id": "arithmetic",        "name": "Arithmetic",        "url": "/browse/elementary/math/arithmetic",        "parent": "Math", "pages": 2},
    {"id": "mental-math",       "name": "Mental Math",       "url": "/browse/elementary/math/mental-math",       "parent": "Math", "pages": 1},
    {"id": "math-test-prep",    "name": "Math Test Prep",    "url": "/browse/elementary/math/math-test-prep",    "parent": "Math", "pages": 2},
    {"id": "ms-algebra",        "name": "MS Algebra",        "url": "/browse/middle-school/math/algebra",        "parent": "Math", "pages": 2},
    {"id": "ms-fractions",      "name": "MS Fractions",      "url": "/browse/middle-school/math/fractions",      "parent": "Math", "pages": 1},
    {"id": "ms-geometry",       "name": "MS Geometry",       "url": "/browse/middle-school/math/geometry",       "parent": "Math", "pages": 1},
    {"id": "hs-algebra",        "name": "HS Algebra",        "url": "/browse/high-school/math/algebra",          "parent": "Math", "pages": 2},
    {"id": "hs-geometry",       "name": "HS Geometry",       "url": "/browse/high-school/math/geometry",         "parent": "Math", "pages": 1},
    {"id": "statistics",        "name": "Statistics",        "url": "/browse/high-school/math/statistics",       "parent": "Math", "pages": 1},
    {"id": "calculus",          "name": "Calculus",          "url": "/browse/high-school/math/calculus",         "parent": "Math", "pages": 1},
    {"id": "precalculus",       "name": "Precalculus",       "url": "/browse/high-school/math/precalculus",      "parent": "Math", "pages": 1},

    # ─── SCIENCE ──────────────────────────────────────────────────────────────
    {"id": "1st-grade-science", "name": "1st Grade Science", "url": "/browse/elementary/1st-grade/science",    "parent": "Science", "pages": 2},
    {"id": "2nd-grade-science", "name": "2nd Grade Science", "url": "/browse/elementary/2nd-grade/science",    "parent": "Science", "pages": 2},
    {"id": "3rd-grade-science", "name": "3rd Grade Science", "url": "/browse/elementary/3rd-grade/science",    "parent": "Science", "pages": 3},
    {"id": "4th-grade-science", "name": "4th Grade Science", "url": "/browse/elementary/4th-grade/science",    "parent": "Science", "pages": 3},
    {"id": "5th-grade-science", "name": "5th Grade Science", "url": "/browse/elementary/5th-grade/science",    "parent": "Science", "pages": 3},
    {"id": "6th-grade-science", "name": "6th Grade Science", "url": "/browse/middle-school/6th-grade/science", "parent": "Science", "pages": 2},
    {"id": "7th-grade-science", "name": "7th Grade Science", "url": "/browse/middle-school/7th-grade/science", "parent": "Science", "pages": 2},
    {"id": "8th-grade-science", "name": "8th Grade Science", "url": "/browse/middle-school/8th-grade/science", "parent": "Science", "pages": 2},
    {"id": "high-school-science","name": "High School Science","url": "/browse/high-school/science",            "parent": "Science", "pages": 2},
    {"id": "kindergarten-science","name":"Kindergarten Science","url":"/browse/elementary/kindergarten/science","parent": "Science", "pages": 1},
    {"id": "biology",           "name": "Biology",           "url": "/browse/science/biology",                  "parent": "Science", "pages": 3},
    {"id": "earth-sciences",    "name": "Earth Sciences",    "url": "/browse/science/earth-sciences",           "parent": "Science", "pages": 2},
    {"id": "chemistry",         "name": "Chemistry",         "url": "/browse/science/chemistry",                "parent": "Science", "pages": 2},
    {"id": "physics",           "name": "Physics",           "url": "/browse/science/physics",                  "parent": "Science", "pages": 1},
    {"id": "physical-science",  "name": "Physical Science",  "url": "/browse/science/physical-science",         "parent": "Science", "pages": 2},
    {"id": "astronomy",         "name": "Astronomy",         "url": "/browse/science/astronomy",                "parent": "Science", "pages": 1},

    # ─── SOCIAL STUDIES ───────────────────────────────────────────────────────
    {"id": "3rd-grade-ss",      "name": "3rd Grade Social Studies", "url": "/browse/elementary/3rd-grade/social-studies",    "parent": "Social Studies", "pages": 2},
    {"id": "4th-grade-ss",      "name": "4th Grade Social Studies", "url": "/browse/elementary/4th-grade/social-studies",    "parent": "Social Studies", "pages": 2},
    {"id": "5th-grade-ss",      "name": "5th Grade Social Studies", "url": "/browse/elementary/5th-grade/social-studies",    "parent": "Social Studies", "pages": 2},
    {"id": "6th-grade-ss",      "name": "6th Grade Social Studies", "url": "/browse/middle-school/6th-grade/social-studies", "parent": "Social Studies", "pages": 2},
    {"id": "7th-grade-ss",      "name": "7th Grade Social Studies", "url": "/browse/middle-school/7th-grade/social-studies", "parent": "Social Studies", "pages": 2},
    {"id": "8th-grade-ss",      "name": "8th Grade Social Studies", "url": "/browse/middle-school/8th-grade/social-studies", "parent": "Social Studies", "pages": 2},
    {"id": "high-school-ss",    "name": "High School Social Studies","url": "/browse/high-school/social-studies",             "parent": "Social Studies", "pages": 2},
    {"id": "us-history",        "name": "US History",        "url": "/browse/social-studies/us-history",        "parent": "Social Studies", "pages": 3},
    {"id": "world-history",     "name": "World History",     "url": "/browse/social-studies/world-history",     "parent": "Social Studies", "pages": 2},
    {"id": "geography",         "name": "Geography",         "url": "/browse/social-studies/geography",         "parent": "Social Studies", "pages": 2},
    {"id": "government",        "name": "Government",        "url": "/browse/social-studies/government",        "parent": "Social Studies", "pages": 2},
    {"id": "economics",         "name": "Economics",         "url": "/browse/social-studies/economics",         "parent": "Social Studies", "pages": 1},
    {"id": "ancient-history",   "name": "Ancient History",   "url": "/browse/social-studies/ancient-history",   "parent": "Social Studies", "pages": 2},
    {"id": "european-history",  "name": "European History",  "url": "/browse/social-studies/european-history",  "parent": "Social Studies", "pages": 1},
    {"id": "native-americans",  "name": "Native Americans",  "url": "/browse/social-studies/native-americans",  "parent": "Social Studies", "pages": 1},
    {"id": "middle-ages",       "name": "Middle Ages",       "url": "/browse/social-studies/middle-ages",       "parent": "Social Studies", "pages": 1},
    {"id": "psychology",        "name": "Psychology",        "url": "/browse/social-studies/psychology",        "parent": "Social Studies", "pages": 1},

    # ─── LANGUAGES ────────────────────────────────────────────────────────────
    {"id": "spanish",   "name": "Spanish",   "url": "/browse/world-languages/spanish",   "parent": "Languages", "pages": 3},
    {"id": "french",    "name": "French",    "url": "/browse/world-languages/french",    "parent": "Languages", "pages": 2},
    {"id": "chinese",   "name": "Chinese",   "url": "/browse/world-languages/chinese",   "parent": "Languages", "pages": 1},
    {"id": "german",    "name": "German",    "url": "/browse/world-languages/german",    "parent": "Languages", "pages": 1},
    {"id": "japanese",  "name": "Japanese",  "url": "/browse/world-languages/japanese",  "parent": "Languages", "pages": 1},
    {"id": "italian",   "name": "Italian",   "url": "/browse/world-languages/italian",   "parent": "Languages", "pages": 1},
    {"id": "arabic",    "name": "Arabic",    "url": "/browse/world-languages/arabic",    "parent": "Languages", "pages": 1},
    {"id": "latin",     "name": "Latin",     "url": "/browse/world-languages/latin",     "parent": "Languages", "pages": 1},
    {"id": "portuguese","name": "Portuguese","url": "/browse/world-languages/portuguese","parent": "Languages", "pages": 1},
    {"id": "asl",       "name": "ASL",       "url": "/browse/world-languages/american-sign-language", "parent": "Languages", "pages": 1},

    # ─── ARTS ─────────────────────────────────────────────────────────────────
    {"id": "visual-arts",       "name": "Visual Arts",       "url": "/browse/art/visual-arts",                  "parent": "Arts", "pages": 2},
    {"id": "music",             "name": "Music",             "url": "/browse/performing-arts/music",            "parent": "Arts", "pages": 2},
    {"id": "drama",             "name": "Drama",             "url": "/browse/performing-arts/drama",            "parent": "Arts", "pages": 1},
    {"id": "dance",             "name": "Dance",             "url": "/browse/performing-arts/dance",            "parent": "Arts", "pages": 1},
    {"id": "art-history",       "name": "Art History",       "url": "/browse/art/art-history",                  "parent": "Arts", "pages": 1},
    {"id": "graphic-arts",      "name": "Graphic Arts",      "url": "/browse/art/graphic-arts",                 "parent": "Arts", "pages": 1},
    {"id": "instrumental-music","name": "Instrumental Music","url": "/browse/performing-arts/instrumental-music","parent": "Arts", "pages": 1},
    {"id": "vocal-music",       "name": "Vocal Music",       "url": "/browse/performing-arts/vocal-music",      "parent": "Arts", "pages": 1},
    {"id": "music-composition", "name": "Music Composition", "url": "/browse/performing-arts/music-composition","parent": "Arts", "pages": 1},

    # ─── SPECIAL EDUCATION ────────────────────────────────────────────────────
    {"id": "special-education", "name": "Special Education", "url": "/browse/special-education", "parent": "Special Ed", "pages": 3},
    {"id": "speech-therapy",    "name": "Speech Therapy",    "url": "/browse/speech-therapy",    "parent": "Special Ed", "pages": 2},
    {"id": "life-skills",       "name": "Life Skills",       "url": "/browse/special-education/life-skills", "parent": "Special Ed", "pages": 1},

    # ─── SOCIAL EMOTIONAL ─────────────────────────────────────────────────────
    {"id": "sel",                   "name": "Social Emotional Learning","url": "/browse/social-emotional/social-emotional-learning", "parent": "Social Emotional", "pages": 3},
    {"id": "character-education",   "name": "Character Education",     "url": "/browse/social-emotional/character-education",       "parent": "Social Emotional", "pages": 2},
    {"id": "classroom-community",   "name": "Classroom Community",     "url": "/browse/social-emotional/classroom-community",       "parent": "Social Emotional", "pages": 2},
    {"id": "school-counseling",     "name": "School Counseling",       "url": "/browse/social-emotional/school-counseling",         "parent": "Social Emotional", "pages": 1},
    {"id": "school-psychology",     "name": "School Psychology",       "url": "/browse/social-emotional/school-psychology",         "parent": "Social Emotional", "pages": 1},

    # ─── SPECIALTY ────────────────────────────────────────────────────────────
    {"id": "physical-education",    "name": "Physical Education",      "url": "/browse/physical-education",                         "parent": "Specialty", "pages": 2},
    {"id": "health",                "name": "Health",                  "url": "/browse/health",                                     "parent": "Specialty", "pages": 1},
    {"id": "cte",                   "name": "Career & Technical Ed",   "url": "/browse/specialty/career-and-technical-education",   "parent": "Specialty", "pages": 1},
    {"id": "professional-dev",      "name": "Professional Development","url": "/browse/specialty/professional-development",          "parent": "Specialty", "pages": 1},
    {"id": "cooking",               "name": "Cooking",                 "url": "/browse/specialty/cooking",                          "parent": "Specialty", "pages": 1},
    {"id": "child-care",            "name": "Child Care",              "url": "/browse/specialty/child-care",                       "parent": "Specialty", "pages": 1},
    {"id": "occupational-therapy",  "name": "Occupational Therapy",    "url": "/browse/specialty/occupational-therapy",             "parent": "Specialty", "pages": 1},
    {"id": "physical-therapy",      "name": "Physical Therapy",        "url": "/browse/specialty/physical-therapy",                 "parent": "Specialty", "pages": 1},
    {"id": "vocational-education",  "name": "Vocational Education",    "url": "/browse/specialty/vocational-education",             "parent": "Specialty", "pages": 1},
    {"id": "service-learning",      "name": "Service Learning",        "url": "/browse/specialty/service-learning",                 "parent": "Specialty", "pages": 1},
    {"id": "coaching",              "name": "Coaching",                "url": "/browse/specialty/coaching",                         "parent": "Specialty", "pages": 1},
]

# Vérification du total de requêtes
SORT_ORDERS = ["Most-Reviewed", "Highest-Rated", "Most-Recent"]

def get_total_requests():
    return sum(cat["pages"] * len(SORT_ORDERS) for cat in TPT_LEAF_CATEGORIES)
